### ISSUE TITLE
Stmt#, FollowsStar, Uses, Modifies, procName, value

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#11]
**stmt s, s1; variable v; procedure p; constant c;Select s such that Follows\* (s1, s) with s1.stmt#= 1 such that Uses (s, v) and Modifies (p, v) with p.procName="Mary" and s.stmt#=c.value**
Your answer: 
Correct answer: 2 3 4 5 
Missing: 2 3 4 5

**Comment by Cryrivers** [comment]
QP: parsed:  6, merged:  0, discard:  2, result:  4.

QueryVariableTable:
1. MapTo[  0] Origin[        s] Type[        stmt] Content[ -1] Depd[ 0] Count[ 4]
2. MapTo[  1] Origin[       s1] Type[    stmt_num] Content[  1] Depd[-1] Count[ 1]
3. MapTo[  2] Origin[        v] Type[    variable] Content[ -1] Depd[ 0] Count[ 2]
4. MapTo[  3] Origin[        p] Type[  known_proc] Content[  1] Depd[-1] Count[ 1]
5. MapTo[  4] Origin[        c] Type[    constant] Content[ -1] Depd[-1] Count[ 1]

TargetVariable: 
1. Var[  0] HasA[0] Attr[            ]

QueryClauseTable:
1. Rel[Follows\*  ] Var1[ 1] Var2[ 0] Typ3[1573355985] Var3[] 
2. Rel[UsesS     ] Var1[ 0] Var2[ 2] Typ3[1573355985] Var3[] 
3. Rel[ModifiesP ] Var1[ 3] Var2[ 2] Typ3[1573355985] Var3[] 
4. Rel[with      ] Var1[ 0] Var2[ 4] Attr1[       stmt_num] Attr2[          value] Typ3[2917200] Var3[]

**Comment by haoqiang** [comment]
Select s such that Follows\* (s1, s) with s1.stmt#= 1  =>  2,3,4,6,8,9

No 5, preprocessor looks fine~

**Comment by haoqiang** [comment]
5 is call again! Same with the other one.

**Comment by Cryrivers** [comment]
@haoqiang. Follows Table bug is fixed. Still no answer.

**Comment by zhenming** [comment]
yue cong check, haoqiang passed me the correct information..

all the clauses seem correct except for with..

this is what i called with
vector 1 -> (2,3,4,5,6,7,8,9,18)
vector 2 -> (10,5,4,12,1,1,3,2,1,1)
WITH_STMTNUMBER
WITH_VALUE
arg -> 2

I think pkb controller returns false?

**Comment by yc1111** [comment]
Same bug fixed
