### ISSUE TITLE
Next, Parent, Modifies, Uses

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#12]
**prog_line n1; stmt s; if ifstat; while w; variable v; Select n1 such that Next (n1, s) and Parent (ifstat, s) and Modifies (w, v) and Uses (s, v)**
Your answer: 1 2 3 4 5 6 7 8 9 10 11 11 12 13 14 15 16 17 17 19 20 21 22 22 24 25 25 27 28 28 29 30 
Correct answer: 11 12 14 15 28 
Additional: 1 10 13 16 17 19 2 20 21 22 24 25 27 29 3 30 4 5 6 7 8 9

**Comment by Cryrivers** [comment]
QP: parsed:  4, merged:  0, discard:  0, result:  4.

QueryVariableTable:
1. MapTo[  0] Origin[       n1] Type[   prog_line] Content[ -1] Depd[ 0] Count[ 2]
2. MapTo[  1] Origin[        s] Type[        stmt] Content[ -1] Depd[ 1] Count[ 3]
3. MapTo[  2] Origin[   ifstat] Type[          if] Content[ -1] Depd[-1] Count[ 1]
4. MapTo[  3] Origin[        w] Type[       while] Content[ -1] Depd[-1] Count[ 1]
5. MapTo[  4] Origin[        v] Type[    variable] Content[ -1] Depd[ 1] Count[ 2]

TargetVariable: 
1. Var[  0] HasA[0] Attr[            ]

QueryClauseTable:
1. Rel[Next      ] Var1[ 0] Var2[ 1] Typ3[1573355985] Var3[] 
2. Rel[Parent    ] Var1[ 2] Var2[ 1] Typ3[1573355985] Var3[] 
3. Rel[ModifiesS ] Var1[ 3] Var2[ 4] Typ3[1573355985] Var3[] 
4. Rel[UsesS     ] Var1[ 1] Var2[ 4] Typ3[1573355985] Var3[]

**Comment by Cryrivers** [comment]
This is query 57. @u0905191 please check this with @yc1111 . I'll also check if parser add wrong things to the table.

**Comment by u0905191** [comment]
The produced answer suggests that only Next(n1, s) is evaluated. The other 3 relations are not evaluated.

**Comment by zhenming** [comment]
haoqiang please check..

this is what you returned for dependency
n1 -> 0
s -> 1
if -> -1
w -> -1
v -> 1

s and v should have the same dependency as n1

**Comment by haoqiang** [comment]
this is a problem with progline I'll fix it now.

**Comment by haoqiang** [comment]
Fixed, how did we passed so many test. :P
