### ISSUE TITLE
CallStar selection

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#13]
**procedure p; Select p such that Calls\* (p, "John")**
Your answer: 
Correct answer: Bill Mary 
Missing: Bill Mary

**Comment by Cryrivers** [comment]
Preprocessor: Look like working properly.
Parser: Add correct entries to Call Table.

**Comment by zhenming** [comment]
I think previously calls\* wasnt available in pkb controller, and hq commented it out in my QE, think yc fixed it already?

**Comment by Cryrivers** [comment]
yc fixed just now. Still no answer produced.
