### ISSUE TITLE
Select BOOLEAN with c.value produces no answer

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#16]
if ifstat; constant c;
Select BOOLEAN pattern ifstat ("i", _, _) with c.value = 10

> Evaluating query 54 - Pattern and With  ::
> Your answer: 
> Correct answer: TRUE 
> Missing: TRUE

**Comment by Cryrivers** [comment]
if ifstat; constant c;
Select BOOLEAN pattern ifstat ("i", _, _) 

This query can not produce any answer either.

`vector<int>* AST::matchIfBranch` is never called.

**Comment by yc1111** [comment]
pattern in pkb is not called also....Have we supported it in QE?

**Comment by Cryrivers** [comment]
We passed this case before.

**Comment by yc1111** [comment]
No way. Since I haven't finish implementing pattern for if and while =.=. I thought I finished that.
Anyway, PKBController::pattern is not called. It needs to be called in QE

**Comment by Cryrivers** [comment]
@yc1111 and @zhenming, please fix it by Tuesday then we can demo to Cristina.

**Comment by zhenming** [comment]
I am still debugging, but haoqiang, there is something wrong in the dependency you gave me

ifstat - you gave me dependency 0 - should b e -1?
BOOLEAN - you gave me dependency 2 - should be -1?

**Comment by zhenming** [comment]
the query is for CS3202Test1Code.c right?

because the dependency given by haoqiang is not correct, it goes into case 2d, when it should go into case 1d.

anyway yuecong, https://docs.google.com/document/d/1eHjvaK_MulGEDR5fePxIfzSx2VIK0JvaekYmtZN72eg/edit why do we do nothing when in case 2d, also i feel the other cases are also a bit weird, maybe we discuss on tuesday..

**Comment by zhenming** [comment]
went into case 3d not 2d.

the input sent:
vectorA - [11,28]
vectorB - [5]
string - ''
patternType - PATTERN_IF
arg - 2

false is returned from PKB

**Comment by Cryrivers** [comment]
we'd better solve this issue by meeting cristina. or i can remove this test case for now. i think it is ok to demo to her with this error.
