### ISSUE TITLE
Program crashes on processing pattern

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#17]
assign a; variable v; stmt s;
Select v such that Modifies(s, v) pattern a(v, _"w"_)

~~This issue is mine.~~

**Comment by Cryrivers** [comment]
I just checked `containTree()` and `containSubtree()`. They returned the correct result.
It's Design Extractor's problem.

![1](https://f.cloud.github.com/assets/1313238/213369/54fb9a54-837c-11e2-8ab0-4db865d173bc.png)
![image](https://f.cloud.github.com/assets/1313238/213368/4fa79b02-837c-11e2-97d5-9479fbc5a74e.png)

**Comment by yc1111** [comment]
Is the answer p;z;??

**Comment by Cryrivers** [comment]
Answer is p, z.
