### ISSUE TITLE
p1.procName = c.procName

### ISSUE THREAD

**Issue by zhenming** [Cryrivers/SPA#19]
haoqiang do not merge this case!!!!

query i tested:

Select c such that Calls(p2,p1) with p1.procName = c.procName and p2.procName = "Main"

**Comment by zhenming** [comment]
refer: https://docs.google.com/document/d/1CEEug7hsKHGgDR2ElNJiAKJ9YXsNBB34YcVDpnPQMaE/edit

**Comment by haoqiang** [comment]
? What did I do?

I'll check later

**Comment by haoqiang** [comment]
= =! This is quite a easy fix.

All attribute of call.procName is AT_CALL_PROC_NAME, I returned a wrong value at one function.

**Comment by Cryrivers** [comment]
so can close this issue now?

**Comment by haoqiang** [comment]
Wait Zhenming to change the evaluator.
