### ISSUE TITLE
c.value error

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#2]
stmt s; constant c;
Select s with s.stmt# = c.value

Correct answer is 1, 2, 3, 4, 5, 10, 12.

Please check. Let us know If your code has no bug.

**Comment by zhenming** [comment]
Haoqiang please check

I think this will be passed to the evaluator to handle, but just now I
tried, I think the evaluator wasnt called at all.

**Comment by haoqiang** [comment]
yes, one case missing again. 

Fixed now. pull from repo.

On 26 Feb, 2013, at 19:45:11 , zhenming notifications@github.com wrote:

> s.stmt# = c.value 

---

This is a mail from Zhang Haoqiang's Gmail account. You are welcomed to send mail to mail@haoqiang.info in the future. It is confidential and may be privileged. If you are not the intended recipient, please delete it and notify me immediately. 
Thank you and have a nice day.  
─────=≡Σ((( っﾟ∀ﾟ)っ

**Comment by Cryrivers** [comment]
Still cannot produce the correct answer :/

**Comment by haoqiang** [comment]
Query table is correct. What is the problem now?

On 28 Feb, 2013, at 09:05:03 , Cryrivers notifications@github.com wrote:

> Still cannot produce the correct answer :/
> 
> —
> Reply to this email directly or view it on GitHub.

---

This is a mail from Zhang Haoqiang's Gmail account. You are welcomed to send mail to mail@haoqiang.info in the future. It is confidential and may be privileged. If you are not the intended recipient, please delete it and notify me immediately. 
Thank you and have a nice day.  
─────=≡Σ((( っﾟ∀ﾟ)っ

**Comment by Cryrivers** [comment]
Evaluating query 47 - stmt#, value  ::
Your answer: 
Correct answer: 1 2 3 4 5 10 12 
Missing: 1 10 12 2 3 4 5 
stmt s; constant c; Select s with s.stmt# = c.value

**Comment by Cryrivers** [comment]
I'm not sure if it's @haoqiang 's problem or @zhenming 's or some one else 's problem.

**Comment by zhenming** [comment]
haoqiang gave me the correct outputs, yue cong check this..

for this case i call pkb with 
1st vector empty
2nd vector (10, 5, 4, 12, 1, 1, 3, 2, 1, 1)
WITH_STMTNUMBER
WITH_VALUE
arg = 2

but i think you return false?

**Comment by Cryrivers** [comment]
This is query 47. For the record,

**Comment by yc1111** [comment]
Is this One to One? Actually I uses follows to handles one to one relations. so i just calls follows(vector1, vector2, arg). If this is one to one. there should not be a problem

**Comment by yc1111** [comment]
Bug fixed
