### ISSUE TITLE
Real infinite loop this time

### ISSUE THREAD

**Issue by haoqiang** [Cryrivers/SPA#21]
---

Query1:
stmt s2,s3; variable v; Select v such that Modifies (s3,v) and Uses(s3,v) and Modifies(s2,v) and Uses (s2,v)

QP: parsed:  4, merged:  0, discard:  0, result:  4.

QueryVariableTable:
1. MapTo[  0] Origin[       s2] Type[        stmt] Content[ -1] Depd[ 2] Count[ 2]
2. MapTo[  1] Origin[       s3] Type[        stmt] Content[ -1] Depd[ 2] Count[ 2]
3. MapTo[  2] Origin[        v] Type[    variable] Content[ -1] Depd[ 2] Count[ 5]

TargetVariable:
1. Var[  2] HasA[0] Attr[            ]

ClauseTable:
Dependency group: [ 2]
1. Rel[ModifiesS ] Var1[ 1] Var2[ 2]
2. Rel[UsesS     ] Var1[ 1] Var2[ 2]
3. Rel[ModifiesS ] Var1[ 0] Var2[ 2]
4. Rel[UsesS     ] Var1[ 0] Var2[ 2]

**Comment by haoqiang** [comment]
Confirmed complexity problem needs optimising.

**Comment by haoqiang** [comment]
try to use a hash set for result.
Currently adding too many duplicate stuff into the duplicate list.

**Comment by zhenming** [comment]
fixed a performance issue in obtaining tuple results, performance improved.. took 9.868s
