### ISSUE TITLE
Currently next seems to be doing interprocedural next?

### ISSUE THREAD

**Issue by zhenming** [Cryrivers/SPA#23]
as above

**Comment by Cryrivers** [comment]
Can turn it off at SPAType.h

Set CFG_BIP_ENABLED to 0.

**Comment by zhenming** [comment]
ok, but it should be under a different relation name??

I mean we need to support next and inter procedural next at the same time?

**Comment by Cryrivers** [comment]
I asked Lei Dong before. He said current Next algorithm can support both intra and inter procedural CFG.

**Comment by Cryrivers** [comment]
I'm not sure. If so, I can generate 2 CFG at the same time.

**Comment by zhenming** [comment]
yea think need to ask lei dong
