### ISSUE TITLE
SPA does not clear result vector on finishing evaluating a query

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#24]
Here's the case:
**Query 1**
Your answer: 1 2 4 6 19 
Correct answer: 1 2 4 6 19 
**Query 2**
Your answer: 1 2 4 6 19 x a l def 
Correct answer: a def l x 
Missing: 
Additional: 1 19 2 4 6 

the additional answer in Query 2 comes from Query 1.

I'm not sure who should be in charge of it.

**Comment by Cryrivers** [comment]
I think result vector needs to be cleared when a new query is about to be evaluated.

or there is some result cache for optimization which is not cleared properly.

**Comment by zhenming** [comment]
i think should be my problem, forgot to clear.. 

fixed it, please check
