### ISSUE TITLE
output for "Select BOOLEAN'

### ISSUE THREAD

**Issue by u0905191** [Cryrivers/SPA#26]
For "Select BOOLEAN' queries, the output should be either "true" or "false".
"true" case is working, but “false" case does not output anything.

**Comment by zhenming** [comment]
is this what we discussed yesterday??

if it is, I have done the check for Query Evaluator already.

Haoqiang, if Query Preprocessor evaluate the query to FALSE, you must check if it is "select BOOLEAN". If it is, you must add false to the result list in Query Processor. I have tried to do it for you, but when the query is false, I cant seem to get query target and query variable from Query Preprocessor.

**Comment by haoqiang** [comment]
ok, I'll handle this
