### ISSUE TITLE
DesignExtractor::affectsStar() is not called

### ISSUE THREAD

**Issue by u0905191** [Cryrivers/SPA#27]
DesignExtractor::affectsStar() is not called when the program is

procedure Main {
    while i {
        a=b;
        b=c;
        c=a; 
    }
}

and the query is
Select BOOLEAN such that Affects\* (4, 2)

**Comment by u0905191** [comment]
This program is in SampleCode/AffectsStar.c
The query is already in SPA.cpp

**Comment by zhenming** [comment]
I ran it, seems like my Query Evaluator wasnt called.

hq,please check

**Comment by haoqiang** [comment]
cause no declare! = =!

I'll fix this.

**Comment by haoqiang** [comment]
plus, result is correct
