### ISSUE TITLE
FollowStar & Statement Selection Bug

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#3]
**stmt s; Select s such that Follows\* (s, 21)**

Your answer: 
Correct answer: 20 
Missing: 20

**Comment by zhenming** [comment]
Haoqiang gave me correct output, yue cong check..

I called followsStar with
vecA empty
vecB (21)
arg 2

I think you returned me false?

**Comment by Cryrivers** [comment]
Same problem as Issue #9.
