### ISSUE TITLE
Intersection Error

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#31]
Firstly, pull the latest version of SPA which includes the new test cases and source code.

**Source:** /SampleCode/TestSets/TestSet2/calls_mod_uses_patterns_source.txt
**Testcase 125**

variable v1; prog_line n1; Select n1 such that Uses(n1,v1) and Uses("testIf",v1) and Uses(n1,"i")

**Your answer:** 1 8 9 10 12 14 15 16 19 20 22 24 25 27 28 29
**Correct answer:** 9 14 16
**Additional:** 1 10 12 15 19 20 22 24 25 27 28 29 8

I guess our program fails to intersect the results.

**Comment by haoqiang** [comment]
= =! Ah~~~
I think we should be correct, at least 1 is indeed right.

**Comment by Cryrivers** [comment]
Oh, I see, I checked that query again just now. If Uses relation is "transitive", by "transitive" I mean:

``` C
procedure testWhile {
1   while a {
2       b = a;
3       while b {
4           c = d;
5           while b{
6               c = d;
            }
7           abc = cba + abc * dbg;
        }
8       call testIf;
    }
}
```

Call Statement is inside the while loop, and the while loop (statement 1) uses variables whichever the Call statement uses. Since procedure testIf uses "i", 1 is one of the correct answers.

@u0905191 and @zhenming  please verify this. I think we are correct and they are wrong again.
