### ISSUE TITLE
patterns not checking var index

### ISSUE THREAD

**Issue by haoqiang** [Cryrivers/SPA#38]
I found pattern does not differ the following two cases:

pattern ("x",_)
pattern ("y",_)

**Comment by Cryrivers** [comment]
I guess it's @yc1111 's issue. Since the expression is underscore, Design Extractor handles this case on its own as far as I know.

**Comment by zhenming** [comment]
on CS3202Test2Code.c, the query

assign a; variable v; Select BOOLEAN pattern a(v, _) with a.stmt# = 2 and v.varName = \"com\" is parsed correctly by query processor and passed to pkb, this query is false, but pkb return true...

list 1 { 2 }
list 2 { 0 }
expr ""
patternType PATTERN_ASSIGN_UNDERSCORE_ONLY
arg 0

**Comment by haoqiang** [comment]
I think design extractor only checks for the pattern, it does not check variables. The variable "com" is not passed.

I think zhenming you can add a check on evaluator.

**Comment by zhenming** [comment]
it is supposed to check for variables

**Comment by yc1111** [comment]
assign a; Select a such that pattern a (\"x\",_)

I run this query, but the pattern is not called. Zhenming, please check this case

**Comment by yc1111** [comment]
Actually, preprocessor return false, is this query wrong?

**Comment by yc1111** [comment]
Statement# = 2, v is not com, please check

**Comment by yc1111** [comment]
stmt# = 1, v is com

**Comment by yc1111** [comment]
oh, I'm sorry, I understand now. Too sleepy
