### ISSUE TITLE
Next* discussion

### ISSUE THREAD

**Issue by haoqiang** [Cryrivers/SPA#39]
```
 procedure First {
```
1.    while i {
2.            if a then {
3.                    a=c;
4.                    if a then {
5.                            a=b; }
6.                    else { while difference{
7.                                    if a then {
8.                                            while i{
9.                                                    call Second;
   1.                                                    a=b;
   2.                                                    if a then {
   3.                                                            call Second;}
   4.                                                    else {   a=b; }}}
   5.                                    else { while i{
   6.                                            a=b;
   7.                                            x=y+(c+d*5);
   8.                                            call Second; }}}}}
   9.            else{   a=0;
   10.                      s=t;}
   11.            while i{
   12.                    a=c;
                 }
         }
       }

Try this: stmt s1,s2; Select s1 such that Next(5,s1)
Our answer:  none
seams node 5 is not connected with node 20

**Comment by haoqiang** [comment]
procedure First { 
    while i {  
        if a then { 
            a=c;
            if a then { 
                a=b; } 
            else { while difference{ 
                    if a then { 
                        while i{
                            call Second;
                            a=b;
                            if a then { 
                                call Second;}
                            else {   a=b; }}} 
                    else { while i{
                        a=b;
                        x=y+(c+d*5);
                        call Second; }}}}}
        else{   a=0;
                s=t;}
        while i{
            a=c;
        }
    }
} 

code break on top.

**Comment by Cryrivers** [comment]
Thanks. I'm trying to fix it.
