### ISSUE TITLE
Pattern & Uses Bug

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#5]
**assign a; if ifstat; variable v; Select a pattern a (_ , _"1"_) such that Uses (ifstat, v) and Uses (a, v)**
Your answer: 29 4 13 16 22 4 
Correct answer: 13 16 22 29 
Additional: 4

**Comment by Cryrivers** [comment]
This is query 41.

**Comment by u0905191** [comment]
Statement 4 is
d = x + y \* 12;
Is it considered an answer since "x+y*12" contains "1".

**Comment by Cryrivers** [comment]
yeah, it is my issue. I'm working on it.
