### ISSUE TITLE
Output Statement Number without checking

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#6]
**stmt s; Select s with s.stmt# = 100**
Your answer: 100 
Correct answer: 
Additional: 100

**Comment by yc1111** [comment]
Can check getAllStmt to know the size

**Comment by Cryrivers** [comment]
is it your issue or @zhenming 's issue?

**Comment by yc1111** [comment]
zhen ming's

**Comment by yc1111** [comment]
either zhen ming or haoqiang

**Comment by zhenming** [comment]
haoqiang, do you do the check?

**Comment by haoqiang** [comment]
My output is ok, like I show you on Tuesday.
Can you make some output?

On 28 Feb, 2013, at 12:33:40 , zhenming notifications@github.com wrote:

> haoqiang, do you do the check?
> 
> —
> Reply to this email directly or view it on GitHub.

---

This is a mail from Zhang Haoqiang's Gmail account. You are welcomed to send mail to mail@haoqiang.info in the future. It is confidential and may be privileged. If you are not the intended recipient, please delete it and notify me immediately. 
Thank you and have a nice day.  
─────=≡Σ((( っﾟ∀ﾟ)っ

**Comment by zhenming** [comment]
haoqiang, similar to issue 7, I think the preprocessor should handle:

https://docs.google.com/document/d/1CEEug7hsKHGgDR2ElNJiAKJ9YXsNBB34YcVDpnPQMaE/edit
4) Convert to Known types, return false if ‘IDENT’ and INTEGER does not exists.

in this case, "stmt s; Select s with s.stmt# = 100"

there is no statement no. 100, so you shouldn't change it to KT_STMT_NUM, but immediately return false

**Comment by Cryrivers** [comment]
QueryVariableTable:
1. MapTo[  0] Origin[        s] Type[    stmt_num] Content[100] Depd[-1] Count[ 1]

TargetVariable: 
1. Var[  0] HasA[0] Attr[            ]

QueryClauseTable:

**Comment by haoqiang** [comment]
Fixed!
