### ISSUE TITLE
Output c.value without checking

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#7]
**constant c; Select c with c.value = 100**
Your answer: 100 
Correct answer: 
Additional: 100

**Comment by zhenming** [comment]
similar to issue 6

**Comment by Cryrivers** [comment]
QP: parsed:  1, merged:  0, discard:  1, result:  0.

QueryVariableTable:
1. MapTo[  0] Origin[        c] Type[ known_const] Content[100] Depd[-1] Count[ 1]

TargetVariable: 
1. Var[  0] HasA[0] Attr[            ]

QueryClauseTable:

**Comment by haoqiang** [comment]
Fixed
