### ISSUE TITLE
Select variable with condition of procName

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#8]
**procedure p; variable v; Select v with p.procName = v.variable**
Your answer: z x y d e i 
Correct answer: 
Additional: d e i x y z

**Comment by Cryrivers** [comment]
@haoqiang 

> QP: parsed:  1, merged:  0, discard:  1, result:  0.
> 
> QueryVariableTable:
> 1. MapTo[  0] Origin[        p] Type[   procedure] Content[ -1] Depd[-1] Count[ 0]
> 2. MapTo[  1] Origin[        v] Type[    variable] Content[ -1] Depd[-1] Count[ 1]
> 
> TargetVariable:
> 0. Var[  1] HasA[0] Attr[            ]

Looks like you shouldn't discard anything.

**Comment by u0905191** [comment]
This query is wrong.

Best regards,
Lei Dong

**Comment by Cryrivers** [comment]
Here's the problem. If the query is wrong. We shouldn't output anything.

**Comment by haoqiang** [comment]
This is my fault! Fixed!

**Comment by u0905191** [comment]
The correct query should be
procedure p; variable v; Select v with p.procName = v.varName

My bad. Zhongliang, could you test the above query?

**Comment by Cryrivers** [comment]
@u0905191  new query looks good. can give a correct answer.

**Comment by Cryrivers** [comment]
@haoqiang I'm kinda worried about the way you fix it.
