### ISSUE TITLE
Follows and Stmt#

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/SPA#9]
**stmt s, s1; Select s such that Follows (s, s1) with s1.stmt#= 21**
Your answer: 
Correct answer: 20 
Missing: 20

**Comment by Cryrivers** [comment]
QP: parsed:  1, merged:  0, discard:  0, result:  1.

QueryVariableTable:
1. MapTo[  0] Origin[        s] Type[        stmt] Content[ -1] Depd[ 0] Count[ 2]
2. MapTo[  1] Origin[       21] Type[    stmt_num] Content[ 21] Depd[-1] Count[ 1]

TargetVariable: 
1. Var[  0] HasA[0] Attr[            ]

QueryClauseTable:
1. Rel[Follows\*  ] Var1[ 0] Var2[ 1] Typ3[1573355985] Var3[]

**Comment by haoqiang** [comment]
Select s such that Follows (s, 21) not right

plus, 21 is a call, check follows table
